# Generated by Django 5.0.6 on 2024-08-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gennder',
            field=models.CharField(default=20, max_length=10),
        ),
    ]
